# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "hello",
    srcs = ["hello_world.cc"],
)

py_binary(
    name = "hello_world_py",
    srcs = ["hello_world_py.py"],
)