# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "demo01_time",
    srcs = ["demo01_time.cc"],
    copts = [],
    deps = ["//cyber"],
)


cc_binary(
    name = "demo02_duration",
    srcs = ["demo02_duration.cc"],
    copts = [],
    deps = ["//cyber"],
)

cc_binary(
    name = "demo03_opt",
    srcs = ["demo03_opt.cc"],
    copts = [],
    deps = ["//cyber"],
)
cc_binary(
    name = "demo04_rate",
    srcs = ["demo04_rate.cc"],
    copts = [],
    deps = ["//cyber"],
)

cc_binary(
    name = "demo05_timer",
    srcs = ["demo05_timer.cc"],
    copts = [],
    deps = ["//cyber"],
)